</div>
<!--================= //Content end ==================-->


<!--================= Footer start ===================-->
<footer id="footer">

<!--======== フッター上部 start ========-->
<div id="footerTop">
<nav class="boxCateNav boxInner clearfix">
	<ul>
	<li><img src="/commonfiles/img/common/ttl-ftr-logo.png" alt="クロニクルリフォーム"></li>
	<li>
		<dl>
		<dt><a href="/">ホーム</a></dt>
		<dd>
			<ul>
			<li><a href="/news/">メディア＆ニュース</a></li>
			<li><a href="/event/">イベント情報</a></li>
			<li><a href="/blog/">スタッフブログ</a></li>
			</ul>
		</dd>
		</dl>
	</li>
	<li>
		<dl>
		<dt><a href="/">クロニクルリフォーム</a></dt>
		<dd>
			<ul>
			<li><a href="/#about">クロニクルリフォームとは</a></li>
			<li><a href="/service/">サービス</a></li>
			<li><a href="/works/">施工事例</a></li>
			<li><a href="/material/">自然素材</a></li>
			</ul>
		</dd>
		</dl>
	</li>
	<li>
		<dl>
		<dt><a href="/plan/">リフォームプラン</a></dt>
		<dd>
			<ul>
			<li><a href="/plan/">デザイナーズプラン</a></li>
			<li><a href="/plan/free_plan.php">自由設計プラン</a></li>
			</ul>
		</dd>
		</dl>
	</li>
	<li>
		<dl>
		<dt><a href="index.php#contact">お問い合わせ</a></dt>
		<dd>
			<ul>
			<li><a href="https://www.chronicle-plus.com/showroom/" target="_blank">ショールーム</a></li>
			</ul>
		</dd>
		</dl>
	</li>
	</ul>

</nav>
</div>
<!--======== フッター上部 end ==========-->

<!--======== フッター中部 start ========-->
<div id="footerMdl">
<div class="boxInner clearfix">

<!--== ▼サイトナビ start ==-->
<nav class="boxSiteNav">
	<ul>
	<li><a href="https://www.propolife.co.jp/" target="_blank">ホーム</a></li>
	<li><a href="https://www.propolife.co.jp/category/news/" target="_blank">ニュース</a></li>
	<li><a href="https://www.propolife.co.jp/%E7%B5%8C%E5%96%B6%E7%90%86%E5%BF%B5/" target="_blank">経営理念</a></li>
	<li><a href="https://www.propolife.co.jp/%E4%BB%A3%E8%A1%A8%E8%80%85%E6%8C%A8%E6%8B%B6/" target="_blank">会社概要</a></li>
	<li><a href="https://www.propolife.co.jp/%E4%B8%BB%E8%A6%81%E4%BA%8B%E6%A5%AD/" target="_blank">事業内容</a></li>
	<li><a href="https://www.propolife.co.jp/recruit/index.html" target="_blank">採用情報</a></li>
	<li><a href="https://www.propolife.co.jp/%E3%82%B5%E3%82%A4%E3%83%88%E3%83%9E%E3%83%83%E3%83%97/" target="_blank">サイトマップ</a></li>
	<li><a href="https://www.propolife.co.jp/form/" target="_blank">お問い合わせ</a></li>
	<li><a href="https://www.propolife.co.jp/%E3%83%97%E3%83%A9%E3%82%A4%E3%83%90%E3%82%B7%E3%83%BC%E3%83%9D%E3%83%AA%E3%82%B7%E3%83%BC/" target="_blank">プライバシーポリシー</a></li>
	</ul>
</nav>
<!--== //サイトナビ end ==-->


<!--== ▼アバウト start ==-->
<div class="boxAbout">
	<dl>
	<dt>株式会社プロポライフ</dt>
	<dd><img src="/commonfiles/img/common/icn-propolife.gif" alt="株式会社プロポライフ"></dd>
	<dd>
	<ul>
	<li>宅地建物取引業 国土交通大臣（2）第7684号</li>
	<li>一級建築士事務所 東京都知事登録 第57946号</li>
	<li>建設業 東京都知事　許可（般‐24）第139064号</li>
	<li>建設業 東京都知事　許可（般‐26）第139064号</li>
	<li>マンション管理業　国土交通大臣（1）第034060号</li>
	</ul>
	</dd>
	</dl>
</div>
<!--== //アバウト end ==-->

</div>
</div>
<!--======== フッター中部 end ==========-->

<!--======== フッター下部 start ========-->
<div id="footerBtm">
<!--== ▼コピーライト start ==-->
<p class="boxCopyright boxInner">
<small>Copyright© CHRONICLE REFORM. All Right Reserved.</small>
</p>
<!--== //コピーライト end ==-->

<!--== ▼ページトップへ戻る start ==-->
<p id="btnPageTop">
<a href="#container"><img src="/commonfiles/img/common/btn-pagetop.png" width="50" height="50" alt="ページトップへ戻る"></a>
</p>
<!--== //ページトップへ戻る end ==-->
</div>
<!--======== フッター下部 end ==========-->

</footer>
<!--================= //Footer end ===================-->

</div>
