<header id="header">
<div class="boxInner">

<!--==== ▼サイトロゴ start ====-->
<h1 id="ttlSiteLogo">
<a href="/"><img src="/commonfiles/img/common/ttl-hdr-logo.png" alt="クロニクルリフォーム"></a>
</h1>
<!--==== //サイトロゴ end ====-->

<!--== ▼グローバルナビ start ==-->
<nav id="boxGlobalNav" class="clearfix">
	<dl>
	<dt class="btnOpen">
	<img src="/commonfiles/img/common/btn-gnav-menu.png" alt="Menu">
	</dt>

	<dd class="boxMenu">
	<ul>
	<li class="btnMedia"><a href="/news/"><span>メディア＆ニュース</span></a></li>
	<li class="btnAbout"><a href="/#about"><span>クロニクルリフォームとは</span></a></li>
	<li class="btnMaterial"><a href="/material/"><span>自然素材</span></a></li>
	<li class="btnService"><a href="/service/"><span>サービス</span></a></li>
	<li class="btnPlan"><a href="/plan/"><span>リフォームプラン</span></a></li>
	<li class="btnWorks"><a href="/works/"><span>施行事例</span></a></li>
	<li class="btnContact"><a href="/#contact"><span>お問い合わせ</span></a></li>
	<li class="btnEvent"><a href="/event/"><span>イベント情報</span></a></li>
	<li class="btnBlog"><a href="/blog/"><span>スタッフブログ</span></a></li>
	</ul>
	<p class="btnClose">CLOSE</p>
	</dd>
	</dl>
</nav>
<!--== //グローバルナビ end ==-->

<!--== ▼お問い合わせ start ==-->
<address class="boxContact clearfix">
	<ul>
	<li>
	<img class="imgMain" src="/commonfiles/img/common/icn-freecall.gif" alt="お問い合わせ・お見積り依頼受付中">
	<a class="btnLinkTel" href="tel:0120-60-2429"><img class="imgSmp" src="/commonfiles/img/common/icn-freecall-smp.gif" alt="お問い合わせ・お見積り依頼受付中"></a>
	</li>
	<li>
	<a class="btnBrown" href="https://www.chronicle-plus.com/showroom/" target="_blank">
	<img class="imgMain" src="/commonfiles/img/common/bnr-showroom.jpg" alt="ショールームのご案内">
	<img class="imgSmp" src="/commonfiles/img/common/bnr-showroom-smp.png" alt="ショールームのご案内">
	</a>
	</li>
	</ul>
</address>
<!--== //お問い合わせ end ==-->

</div>
</header>
